apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ '{{ include "' ~ service_name ~ '.fullname" . }}' }}-config
data:
{{ '{{- range $key, $value := .Values.env }}' }}
  {{ '{{ $key }}' }}: {{ '{{ $value | quote }}' }}
{{ '{{- end }}' }}
