apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ '{{ include "' ~ service_name ~ '.fullname" . }}' }}
  labels:
    app.kubernetes.io/name: {{ '{{ include "' ~ service_name ~ '.name" . }}' }}
spec:
  replicas: {{ '{{ .Values.replicaCount }}' }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ '{{ include "' ~ service_name ~ '.name" . }}' }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ '{{ include "' ~ service_name ~ '.name" . }}' }}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: "{{ '{{ .Values.image.repository }}:{{ .Values.image.tag }}' }}"
          imagePullPolicy: {{ '{{ .Values.image.pullPolicy }}' }}
          ports:
            - name: http
              containerPort: {{ '{{ .Values.service.targetPort }}' }}
          envFrom:
            - configMapRef:
                name: {{ '{{ include "' ~ service_name ~ '.fullname" . }}' }}-config
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
{{ '{{- toYaml .Values.resources | nindent 12 }}' }}
