apiVersion: v1
kind: Service
metadata:
  name: {% raw %}{{ include "example-service.fullname" . }}{% endraw %}
spec:
  type: {% raw %}{{ .Values.service.type }}{% endraw %}
  selector:
    app.kubernetes.io/name: {% raw %}{{ include "example-service.name" . }}{% endraw %}
  ports:
    - name: http
      port: {% raw %}{{ .Values.service.port }}{% endraw %}
      targetPort: http
