apiVersion: v1
kind: Service
metadata:
  name: {{ '{{ include "example-service.fullname" . }}' }}
spec:
  type: {{ '{{ .Values.service.type }}' }}
  selector:
    app.kubernetes.io/name: {{ '{{ include "example-service.name" . }}' }}
  ports:
    - name: http
      port: {{ '{{ .Values.service.port }}' }}
      targetPort: http
