[tool.poetry]
name = "kickstart"
version = "0.1.0"
description = "Project scaffolding CLI"
authors = ["You"]

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.9"
rich = "^13.0"
requests = "^2.31"
toml = "^0.10.2"

[tool.poetry.scripts]
kickstart = "src.cli.main:app"
