# {{ service_name }}

TypeScript Cloudflare Worker generated by kickstart.

This profile is an explicit scaffold contract, not an architecture generator.

## Stack

- Cloudflare Workers runtime
- Wrangler
- Bun package workflow
- Strict TypeScript
- Vitest

## Lifecycle commands

```bash
make install
make check
make dev
make deploy
```

Deploy requires Cloudflare authentication through Wrangler. For CI, prefer `CLOUDFLARE_API_TOKEN`.

## Verification contract

- Run `make check` before handoff; it executes `make typecheck` and `make test`.
- Keep `src/index.ts` on the `ExportedHandler<Env>` contract.
- Keep `tests/worker.test.ts` green for `/healthz` behavior.
- Treat `.kickstart/scaffold.json` as the source of truth for profile identity and lifecycle metadata.

## Lifecycle flow

1. `make install` to install dependencies.
2. `make check` to validate TypeScript and test contracts.
3. `make dev` to run Wrangler locally.
4. `make deploy` after Wrangler auth and binding/secrets setup.

## Project map

- Worker code: `src/index.ts`
- Worker tests: `tests/worker.test.ts`
- Runtime config: `wrangler.toml`, `.dev.vars.example`
- Generated contract docs: `AGENTS.md`, `docs/contracts/README.md`, `docs/operations/README.md`
