# {{ service_name }}

TypeScript Cloudflare Worker generated by Kickstart.

## Stack

- Cloudflare Workers runtime
- Wrangler
- Bun package workflow
- Strict TypeScript
- Vitest

## Commands

```bash
bun install
bun run dev
bun run typecheck
bun run test
bun run deploy
```

Deploy requires Cloudflare authentication through Wrangler. For CI, prefer `CLOUDFLARE_API_TOKEN`.
