# {{ service_name }}

TypeScript service generated by kickstart.

## Stack

- Node.js 22+
- Fastify
- Bun runtime and package workflow
- Strict TypeScript
- Vitest
- Docker-ready runtime

Optional generated service clients live under `src/clients/`.

## Commands

```bash
bun install
bun run dev
bun run test
bun run build
bun start
```

The service listens on `PORT` and defaults to `8080`.
