# {{ service_name }}

C++ service generated by Kickstart.

## Stack

- C++20
- CMake
- Docker multi-stage build

## Commands

```bash
make build
make test
make dev
```

## Project Structure

```text
src/
├── api/
└── model/
tests/
```
