# {{ service_name }}

Rust Cloudflare Worker generated by kickstart.

## Stack

- Cloudflare Workers runtime
- Rust compiled to `wasm32-unknown-unknown`
- `workers-rs`
- Wrangler

## Prerequisites

```bash
rustup target add wasm32-unknown-unknown
cargo install worker-build
bun install
```

`make build` will install `worker-build` automatically. If `rustup` is available, it will also install the wasm target when missing. Non-rustup Rust installations must provide `wasm32-unknown-unknown` manually.

## Commands

```bash
make check
make build
make dev
make deploy
```

Deploy requires Cloudflare authentication through Wrangler. For CI, prefer `CLOUDFLARE_API_TOKEN`.
