# {{ service_name }}

Rust Cloudflare Worker generated by Kickstart.

## Stack

- Cloudflare Workers runtime
- Rust compiled to `wasm32-unknown-unknown`
- `workers-rs`
- Wrangler

## Prerequisites

```bash
rustup target add wasm32-unknown-unknown
cargo install worker-build
bun install
```

## Commands

```bash
make check
make build
make dev
make deploy
```

Deploy requires Cloudflare authentication through Wrangler. For CI, prefer `CLOUDFLARE_API_TOKEN`.
