apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

nameSuffix: -{{ environment }}

patches:
  - target:
      kind: ConfigMap
      name: {{ monorepo_name }}-config
    patch: |-
      - op: replace
        path: /data/APP_ENV
        value: "{{ environment }}"
