"""Data-transfer objects shared across kickstart boundaries."""

from src.model.dto.posthog import PostHogCapturePayload, PostHogCaptureRequest
from src.model.dto.telemetry import (
    CliArtifactKind,
    CliInstallErrorCategory,
    CliInstallOutcome,
    CliInstallProperties,
    CliUpgradeChecksumStatus,
    CliUpgradeErrorCategory,
    CliUpgradeOutcome,
    CliUpgradeProperties,
    EffectiveTelemetry,
    ScaffoldCreateContext,
    ScaffoldCreateErrorCategory,
    ScaffoldCreateOutcome,
    ScaffoldCreateProperties,
    TelemetryDurationBucket,
    TelemetryConsent,
    TelemetryEnvelope,
    TelemetryEvent,
    TelemetryEventName,
    TelemetryIdentityReset,
    TelemetryState,
    TelemetrySuppressionReason,
)
from src.model.dto.upgrade import UNKNOWN_TARGET_VERSION, UpgradeResult, normalize_target_version

__all__ = [
    "CliArtifactKind",
    "CliInstallErrorCategory",
    "CliInstallOutcome",
    "CliInstallProperties",
    "CliUpgradeChecksumStatus",
    "CliUpgradeErrorCategory",
    "CliUpgradeOutcome",
    "CliUpgradeProperties",
    "EffectiveTelemetry",
    "PostHogCapturePayload",
    "PostHogCaptureRequest",
    "ScaffoldCreateContext",
    "ScaffoldCreateErrorCategory",
    "ScaffoldCreateOutcome",
    "ScaffoldCreateProperties",
    "TelemetryConsent",
    "TelemetryDurationBucket",
    "TelemetryEnvelope",
    "TelemetryEvent",
    "TelemetryEventName",
    "TelemetryIdentityReset",
    "TelemetryState",
    "TelemetrySuppressionReason",
    "UNKNOWN_TARGET_VERSION",
    "UpgradeResult",
    "normalize_target_version",
]
