"""Read-only adoption check: does an existing repo match the scaffold standard?

`kickstart adopt --check` inspects a repository that may not have been
generated by kickstart and reports which standard artifacts (the ENG-9
baseline set every scaffold emits) are present, missing, or malformed. It
never writes; applying the standard to a repo is a later, explicit step.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path

from src.utils.error_handling import KickstartError


class AdoptionTargetError(KickstartError):
    """Raised when the adoption target is not an inspectable directory."""

    def __init__(self, target: Path) -> None:
        super().__init__(f"adoption target '{target}' is not an existing directory")


MANIFEST_PATH = ".kickstart/scaffold.json"

STANDARD_ARTIFACTS: tuple[str, ...] = (
    MANIFEST_PATH,
    "AGENTS.md",
    "README.md",
    "Makefile",
    "docs/architecture/",
    "docs/contracts/",
    "docs/operations/",
    "docs/decisions/",
    ".github/workflows/",
)


@dataclass(frozen=True)
class ArtifactStatus:
    """Presence and health of one standard artifact."""

    path: str
    present: bool
    issue: str = ""

    @property
    def ok(self) -> bool:
        return self.present and self.issue == ""


@dataclass(frozen=True)
class AdoptionReport:
    """Result of a read-only adoption check."""

    root: Path
    artifacts: tuple[ArtifactStatus, ...]

    @property
    def complete(self) -> bool:
        return all(status.ok for status in self.artifacts)

    @property
    def missing(self) -> tuple[ArtifactStatus, ...]:
        return tuple(status for status in self.artifacts if not status.ok)

    def to_json(self) -> str:
        """Machine-readable report for agents and CI."""
        payload = {
            "root": str(self.root),
            "complete": self.complete,
            "artifacts": [
                {"path": status.path, "present": status.present, "issue": status.issue}
                for status in self.artifacts
            ],
        }
        return json.dumps(payload, indent=2) + "\n"


def _manifest_issue(manifest_file: Path) -> str:
    """Validate that an existing scaffold manifest is parseable and shaped."""
    try:
        manifest = json.loads(manifest_file.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        return f"unreadable manifest: {error}"

    if not isinstance(manifest, dict):
        return "manifest is not a JSON object"

    missing_keys = [key for key in ("schema_version", "project", "lifecycle") if key not in manifest]
    if missing_keys:
        return f"manifest missing keys: {', '.join(missing_keys)}"

    return ""


def _makefile_issue(makefile: Path) -> str:
    """A Makefile must expose the canonical check verb to count as standard."""
    try:
        content = makefile.read_text(encoding="utf-8")
    except OSError as error:
        return f"unreadable Makefile: {error}"
    if not re.search(r"^check\s*:", content, re.MULTILINE):
        return "Makefile has no 'check' target (the canonical verification verb)"
    return ""


def _artifact_status(root: Path, artifact: str) -> ArtifactStatus:
    """Inspect one standard artifact path."""
    target = root / artifact
    if artifact.endswith("/"):
        present = target.is_dir()
        return ArtifactStatus(path=artifact, present=present, issue="" if present else "missing directory")

    if not target.is_file():
        return ArtifactStatus(path=artifact, present=False, issue="missing file")

    issue = ""
    if artifact == MANIFEST_PATH:
        issue = _manifest_issue(target)
    elif artifact == "Makefile":
        issue = _makefile_issue(target)
    return ArtifactStatus(path=artifact, present=True, issue=issue)


def inspect_repo(root: Path) -> AdoptionReport:
    """Run the read-only adoption check against an existing repository."""
    if not root.is_dir():
        raise AdoptionTargetError(root)

    resolved = root.resolve()
    artifacts = tuple(_artifact_status(resolved, artifact) for artifact in STANDARD_ARTIFACTS)
    return AdoptionReport(root=resolved, artifacts=artifacts)
