"""Read-only adoption check: does an existing repo match the scaffold standard?

`kickstart adopt --check` inspects a repository that may not have been
generated by kickstart and reports two levels against the standard:

- **Level 1 — conformant**: the vendor-neutral interface every repo can adopt
  with any tooling: `AGENTS.md`, `README.md`, a Makefile with the canonical
  `check` verb, the `docs/` skeleton, `.agents/skills/`, and CI workflows.
  The manifest is deliberately not part of this level.
- **Level 2 — managed**: a repo that additionally carries kickstart state —
  a valid `.kickstart/scaffold.json` that can drive the docs projections,
  with the managed docs fence-wrapped so tooling can verify and re-render
  them. The manifest is adoption payoff (it enables `kickstart plan` and the
  roadmapped reconciliation), never a precondition for conformance.

A repo is judged at the highest level it claims: no manifest → judged at
Level 1; manifest present → judged at Level 2. It never writes; applying the
standard to a repo is a later, explicit step.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from src.generator.docs_plan import DocsPlanTargetError, inspect_docs
from src.generator.scaffold_contract import MANIFEST_PATH, load_parsed_manifest
from src.utils.errors import KickstartError, ManifestShapeError


class AdoptionTargetError(KickstartError):
    """Raised when the adoption target is not an inspectable directory."""

    def __init__(self, target: Path) -> None:
        super().__init__(f"adoption target '{target}' is not an existing directory")


AdoptionLevel = Literal["conformant", "managed", "below-standard"]

LEVEL_CONFORMANT: AdoptionLevel = "conformant"
LEVEL_MANAGED: AdoptionLevel = "managed"
LEVEL_BELOW_STANDARD: AdoptionLevel = "below-standard"

LEVEL1_ARTIFACTS: tuple[str, ...] = (
    "AGENTS.md",
    "README.md",
    "Makefile",
    ".agents/skills/",
    "docs/architecture/",
    "docs/contracts/",
    "docs/operations/",
    "docs/decisions/",
    ".github/workflows/",
)

LEVEL2_ARTIFACTS: tuple[str, ...] = (MANIFEST_PATH,)

# The full artifact vocabulary, kept for consumers that enumerate it.
STANDARD_ARTIFACTS: tuple[str, ...] = (*LEVEL2_ARTIFACTS, *LEVEL1_ARTIFACTS)

FENCE_MANAGED_PATH = "managed docs fences"

# Plan statuses that mean "this managed doc is fence-managed" — content drift
# is a plan concern, not an adoption gap.
_FENCE_READY_STATUSES = frozenset({"in-sync", "presence-only", "content-drift"})


@dataclass(frozen=True)
class ArtifactStatus:
    """Presence and health of one standard artifact."""

    path: str
    present: bool
    issue: str = ""
    level: AdoptionLevel = LEVEL_CONFORMANT

    @property
    def ok(self) -> bool:
        return self.present and self.issue == ""


@dataclass(frozen=True)
class AdoptionReport:
    """Result of a read-only adoption check."""

    root: Path
    artifacts: tuple[ArtifactStatus, ...]
    achieved_level: AdoptionLevel
    claimed_level: AdoptionLevel

    @property
    def complete(self) -> bool:
        return self.achieved_level == self.claimed_level != LEVEL_BELOW_STANDARD

    @property
    def missing(self) -> tuple[ArtifactStatus, ...]:
        return tuple(status for status in self.artifacts if not status.ok)

    def to_json(self) -> str:
        """Machine-readable report for agents and CI."""
        payload = {
            "root": str(self.root),
            "complete": self.complete,
            "achieved_level": self.achieved_level,
            "claimed_level": self.claimed_level,
            "artifacts": [
                {
                    "path": status.path,
                    "present": status.present,
                    "issue": status.issue,
                    "level": status.level,
                }
                for status in self.artifacts
            ],
        }
        return json.dumps(payload, indent=2) + "\n"


def _manifest_issue(manifest_file: Path) -> str:
    """Validate that an existing scaffold manifest is parseable and shaped."""
    try:
        manifest = load_parsed_manifest(manifest_file)
    except ManifestShapeError as error:
        return str(error)

    missing_keys = [key for key in ("schema_version", "project", "lifecycle") if key not in manifest]
    if missing_keys:
        return f"manifest missing keys: {', '.join(missing_keys)}"

    return ""


def _makefile_issue(makefile: Path) -> str:
    """A Makefile must expose the canonical check verb to count as standard."""
    try:
        content = makefile.read_text(encoding="utf-8")
    except OSError as error:
        return f"unreadable Makefile: {error}"
    if not re.search(r"^check\s*:", content, re.MULTILINE):
        return "Makefile has no 'check' target (the canonical verification verb)"
    return ""


def _artifact_status(root: Path, artifact: str, level: AdoptionLevel = LEVEL_CONFORMANT) -> ArtifactStatus:
    """Inspect one standard artifact path."""
    target = root / artifact
    if artifact.endswith("/"):
        present = target.is_dir()
        return ArtifactStatus(
            path=artifact, present=present, issue="" if present else "missing directory", level=level
        )

    if not target.is_file():
        return ArtifactStatus(path=artifact, present=False, issue="missing file", level=level)

    issue = ""
    if artifact == MANIFEST_PATH:
        issue = _manifest_issue(target)
    elif artifact == "Makefile":
        issue = _makefile_issue(target)
    return ArtifactStatus(path=artifact, present=True, issue=issue, level=level)


def _fence_readiness_status(resolved: Path) -> ArtifactStatus:
    """One Level 2 status: can the manifest drive fence-managed docs?"""
    try:
        plan = inspect_docs(resolved)
    except DocsPlanTargetError as error:
        return ArtifactStatus(
            path=FENCE_MANAGED_PATH,
            present=False,
            issue=f"manifest cannot drive the docs projections: {error}",
            level=LEVEL_MANAGED,
        )

    not_ready = [
        f"{entry.target} ({entry.status})"
        for entry in plan.entries
        if entry.status not in _FENCE_READY_STATUSES
    ]
    if not_ready:
        return ArtifactStatus(
            path=FENCE_MANAGED_PATH,
            present=True,
            issue=f"not fence-managed: {', '.join(not_ready)}",
            level=LEVEL_MANAGED,
        )
    return ArtifactStatus(path=FENCE_MANAGED_PATH, present=True, issue="", level=LEVEL_MANAGED)


def inspect_repo(root: Path) -> AdoptionReport:
    """Run the read-only adoption check against an existing repository."""
    if not root.is_dir():
        raise AdoptionTargetError(root)

    resolved = root.resolve()
    level1 = tuple(_artifact_status(resolved, artifact) for artifact in LEVEL1_ARTIFACTS)

    manifest_path = resolved / MANIFEST_PATH
    # Anything occupying the manifest path is a managed claim — including a
    # directory or broken symlink, which must fail the claim rather than
    # silently demote the repo to a passing Level 1.
    manifest_claimed = manifest_path.exists() or manifest_path.is_symlink()
    claimed_level: AdoptionLevel = LEVEL_MANAGED if manifest_claimed else LEVEL_CONFORMANT

    level2: tuple[ArtifactStatus, ...] = ()
    if manifest_claimed:
        manifest_status = _artifact_status(resolved, MANIFEST_PATH, level=LEVEL_MANAGED)
        level2 = (manifest_status,)
        if manifest_status.ok:
            # A broken manifest is one gap, not two: fence readiness re-parses
            # the same file, so only report it when the manifest itself is fine.
            level2 = (manifest_status, _fence_readiness_status(resolved))

    achieved_level: AdoptionLevel = LEVEL_BELOW_STANDARD
    if all(status.ok for status in level1):
        managed_ok = manifest_claimed and all(status.ok for status in level2)
        achieved_level = LEVEL_MANAGED if managed_ok else LEVEL_CONFORMANT

    return AdoptionReport(
        root=resolved,
        artifacts=(*level1, *level2),
        achieved_level=achieved_level,
        claimed_level=claimed_level,
    )
