# {{ monorepo_name }}

Opinionated application workspace generated by kickstart.

## Profile

- Languages: Python, Rust, TypeScript, C++, SQL
- TypeScript workspace: Bun + Turbo
- Local runtime: Docker Compose with PostgreSQL and Redis
- Runtime target: {{ runtime_label }}
- Deployment tool: {{ deployment_tool }}
- Cloud target: {{ cloud_label }}
- Knowledge base: {{ knowledge }}

## Layout

- `apps/` - deployable TypeScript apps and frontends
- `packages/` - shared TypeScript packages
- `services/` - Python, Rust, C++, or TypeScript services
- `config/` - shared TypeScript, lint, and tool config
- `infra/docker/` - local Docker Compose stack
{% if uses_kubernetes -%}
- `infra/k8s/` - Kubernetes base and environment overlays
- `infra/helm/` - Helm chart when generated with `--helm`
{% endif -%}
{% if uses_cloudflare_workers -%}
- `infra/cloudflare/workers/` - Cloudflare Workers runtime notes and route examples
{% endif -%}
- `infra/terraform/` - environment-scoped Terraform entrypoints
{% if include_cloudflare or uses_cloudflare_workers -%}
- Cloudflare support expects `CLOUDFLARE_API_TOKEN` in your shell or CI secrets before managing Cloudflare resources.
{% endif -%}
- `data/postgres/` - SQL schema seed and migration starting point
- `knowledge/` - durable project memory and entity/context notes
- `docs/` - architecture, ADRs, data notes, runbooks, and knowledge-base files
- `reports/` - scratch reports to review before intentionally committing
- `catalog-info.yaml` - Backstage catalog metadata when generated
- `.obsidian/` - Obsidian vault settings when generated

## First Commands

```bash
make install
make test
make compose-up
{% if uses_kubernetes -%}
make k8s-render ENV=dev
{% endif -%}
{% if uses_cloudflare_workers -%}
make cf-worker-notes
{% endif -%}
make tf-plan ENV=dev
```

Review `docs/adr/0001-stack-profile.md` before adding production resources.
